deploy:
  runs-on: windows-latest
  needs: build
  steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: .net-app
        path: ./drop

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'CRUDEF20250927000246'
        package: ./drop
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        # slot-name: 'production'   # add ONLY if you actually have a slot
